### ISSUE TITLE
Avoid JSON.stringify hack when testing responses of fetch-mock

### ISSUE THREAD

**Issue by oscard0m** [octokit/core.js#588]
Affected repos:
- https://github.com/octokit/rest.js/pull/305
- https://github.com/octokit/core.js/pull/563
- https://github.com/octokit/action.js/pull/513
- https://github.com/octokit/auth-app.js/pull/498
- https://github.com/octokit/oauth-app.js/pull/343

---

- [x] octokit/core.js#590
- [x] octokit/rest.js#328
- [x] octokit/action.js#515
- [x] octokit/auth-app.js#506
- [x] octokit/oauth-app.js#437

---
              this should not be necessary, but if it's tricky we can do a follow up issue. It slows down tests, makes order of keys significant, and will be harder to debug when they don't match.

_Originally posted by @gr2m in https://github.com/octokit/core.js/pull/563#discussion_r1258600840_

**Comment by oscard0m** [comment]
I took a look into it. 

The `toStrictEqual` is doing [some customTesters internally](https://github.com/jestjs/jest/blob/2499cf2a3a75824fd0c9b454baa95fc75929f086/packages/expect/src/matchers.ts#L62-L67). The one giving problems is [`typeEquality`](https://github.com/jestjs/jest/blob/2499cf2a3a75824fd0c9b454baa95fc75929f086/packages/expect-utils/src/utils.ts#L372-L387). Concretely, this comparison: `a.constructor === b.constructor`.

When using `fetch-mock`, the accepted type for `response` parameter in `getOnce(matcher, response)` are:

```ts
type MockResponse = Response | Promise<Response>
                        | number | Promise<number>
                        | string | Promise<string>
                        | {} | Promise<{}>
                        | MockResponseObject | Promise<MockResponseObject>;
```

According to [this code comment](https://github.com/gr2m/fetch-mock/blob/1bdac54e1b482398cca0af9658a500de23e72367/types/index.d.ts#L114-L115):

> * object: As long as the object is not a MockResponseObject it is
     *  converted into a json string and returned as the body of a 200 response

This means the `constructor` equal comparison is lost at this point.[^1][^2]

Considering these are mocks controlled by ourselves, the alternatives I come up with are:
a) to use a `jest.toEqual`
b) to keep the hack `of JSON.stringify`
c) try if passing a `MockResponseObject` or `Response` gets the right constructor and `toStrictEqual` works.

[^1]: https://github.com/gr2m/fetch-mock/blob/1bdac54e1b482398cca0af9658a500de23e72367/src/lib/fetch-handler.js#L268-L278
[^2]: https://github.com/gr2m/fetch-mock/blob/1bdac54e1b482398cca0af9658a500de23e72367/src/lib/response-builder.js#L113

**Comment by kfcampbell** [comment]
I think I have a weak preference in favor of `jest.ToEqual`. I had to remind myself of the differences when looking at `.toStrictEqual docs`:

- keys with undefined properties are checked, e.g. `{a: undefined, b: 2}` will not equal `{b: 2}`;
- undefined items are taken into account, e.g. `[2]` will not equal `[2, undefined]`;
- array sparseness is checked, e.g. `[, 1]` will not equal `[undefined, 1]`;
- object types are checked, e.g. a class instance with fields `a` and `b` will not equal a literal object with fields `a` and `b`.

None of those seem deal-breaking to me, though I'd be interested to hear others' thoughts.

**Comment by oscard0m** [comment]
> I think I have a weak preference in favor of `jest.ToEqual`.

+1 👍🏽

**Comment by gr2m** [comment]
> Thumbs up reaction (👍🏽) for `jest.ToEqual`, and I can apply the changes here:

👍🏼 from me, thank you @oscard0m for taking on this and other chore tasks 💛

**Comment by wolfy1339** [comment]
There is at least one case where I switched to `toMatchObject()`

Those could probably be updated as well

**Comment by oscard0m** [comment]
Thank you all for the quick reviews. We are done with this. 🥳 🎆 🍾
